Why Numby?

Takes way less bytes than lists
Lots more to do in terms of math, graphs, pandas, images, Machine Learning (Tensors )etc ..


In [3]:
import numpy as np

# The Basics

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
#Get dims
a.ndim

1

In [12]:
#Get shape
a.shape
b.shape


(2, 3)

In [14]:
# Get Type and specify type

a = np.array([1,2,3], dtype = 'int16')
a.dtype

dtype('int16')

In [17]:
# Get size : Number of elements 
b.size
# Total size : num of bytes : b.size * b.itemsize
b.itemsize
b.nbytes

48

# Accessing/ Changing specific elements, rows, etc

In [4]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r c]

a[0][:-3]

array([1, 2, 3, 4])

In [1]:
# Get a specific row
a[0,:]

# Column 
a[:,-1]

NameError: name 'a' is not defined

In [27]:
# Getting a little more fancy[ start index, end index: step size]

a[0,1:6:2]

array([2, 4, 6])

In [33]:
# Replace value
a[1,5] = 20

a[:,2] = [1,2]
a


array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [48]:
# 3D example

b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Get specific element: 4

b[0,1,1]

4

# Initializing Different Types of Arrays


In [62]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3,3))
#Same with ones, eye, 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
# Any number 
np.full((2,2),74)

np.full_like(a,4) #same size
np.full_like(a.shape,4)

array([4, 4])

In [75]:
#random decemils
np.random.rand(4,2)
#same size as a
np.random.random_sample(a.shape)
#random int
np.random.randint(8, size=(3,3)) # must specify shape # 8 is starting point but inconclusive 
#identity 
np.identity(5)
#repeat an array
arr = np.array ([[1,2,3]]) #Note 2D array 
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [117]:
A = np.ones((5,5))
A
Z = np.zeros((3,3)) 
Z[1,1]=9
A[1:4,1:4] = Z
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# ## Becareful when copying arrays!!

In [122]:
a = np.array([1,2,3])
b = a
b[0] =100
# Note that a changes with b so contents of a is lost
# To make sure to copy a contents 
a = np.array([1,2,3])
b = a.copy()
b[0]=100
a

array([1, 2, 3])

# Math

In [132]:
#Elemental operations
aa = np.array([1,2,3,4])
aa * 2

#Matrices
bb = np.array([1,0,1,0])
aa + bb
aa * bb
aa ** 2
np.sin(aa)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [139]:
A = np.ones((2,3))
print(A)
B = np.full((3,2),2)
print(B)
#Columns  of the first matrix must equal the rows of the second one
# Result much be the same number of rows of the first and columns of the second
A@B # or use matmul

# Find the determint 
c = np.identity(3) # Det(identity) ==1
np.linalg.det(c)

#Eignvalues
#Inverse of matrix
#

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


1.0

# Statistics 

In [150]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
np.min(stats) # The min value
np.min(stats, axis =1) # min of each row
np.max(stats, axis=0) # Max of each row


[[1 2 3]
 [4 5 6]]


array([3, 6])

In [153]:
# Reorganizing Arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [156]:
# Vertically stacking vectors

v1 = np.array ([1,2,3,4])
v2 = np.array ([5,6,7,8])

np.vstack([v1,v2,v1,v2]) #One on another 

#Herozontial stack is simmilar 

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Additional Stuff

In [163]:
filedata = np.genfromtxt('data.txt',delimiter=',') # Autofloat

filedata.astype('int32') # Makes copy 
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# Advanced Intexing & Boolean MAsking 

In [166]:
filedata > 50 # T OR F

# Grab the values bigger than 50

filedata [filedata > 50]



array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [169]:
# Index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [171]:
np.any( filedata >50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [172]:
np.all( filedata >50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [174]:
((filedata) > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [180]:
## Quiz

A = np.array((6,5))
A

array([6, 5])

In [181]:
1:30

SyntaxError: illegal target for annotation (<ipython-input-181-c281485750fd>, line 1)

In [182]:
(1,30,1)

(1, 30, 1)

In [226]:
A = np.array(range(1,31,1))
A = A.reshape(6,5)
print(A)
#index 
A[2:4,0:2]

#index diagnal 
np.diag(A[0:4,1:5])
A

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [235]:
# More index
A[(0,4,5),3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])